language: android
before_script:
- openssl aes-256-cbc -K $encrypted_d5896aca80a4_key -iv $encrypted_d5896aca80a4_iv
  -in xausky.jks.enc -out ../xausky.jks -d
- curl -L https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip -O
- unzip -q android-ndk-r14b-linux-x86_64.zip
- export ANDROID_NDK_HOME="$PWD/android-ndk-r14b"

android:
  components:
  - build-tools-26.0.2
script:
  - "./gradlew assembleRelease"